#!/bin/bash

source /opt/wordpress_scripts/config/script.conf

mysql --disable-column-names -u$admin_mysql -p$mysql_passwd dbispconfig -se "select web_domain.domain from web_domain" >> /opt/wordpress_scripts/config/.list
