#! /bin/bash

source /opt/wordpress_scripts/config/script.conf

echo $(mysql --disable-column-names -u$admin_mysql -p$mysql_passwd dbispconfig -se "select web_database_user.database_user from web_database_user where web_database_user.database_user_id = (select web_database.database_user_id from web_database where web_database.database_name = '$1')")